#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ‘10.0’

target 'PNews' do
    use_frameworks!
    
    pod 'AlamofireImage'
    pod 'SwiftMessages'
    pod 'NVActivityIndicatorView'
    pod 'IQKeyboardManagerSwift'
    pod 'AlamofireObjectMapper'
    pod 'SkyFloatingLabelTextField'

end

